apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voxbank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: voxbank.local
    http:
      paths:
      - path: /api/orchestrator
        pathType: Prefix
        backend:
          service:
            name: orchestrator-service
            port:
              number: 8000
      - path: /api/bank
        pathType: Prefix
        backend:
          service:
            name: mock-bank-service
            port:
              number: 8001

