apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-bank
  template:
    metadata:
      labels:
        app: mock-bank
    spec:
      containers:
      - name: mock-bank
        image: voxbank/mock-bank:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: mock-bank-service
spec:
  selector:
    app: mock-bank
  ports:
  - port: 8001
    targetPort: 8001

